version: 2
jobs:
  test:
    docker:
    - image: circleci/golang:1.11
    working_directory: /go/app
    steps:
    - checkout
    - run: go test -v github.com/zegl/kube-score/...

  # This step is identical to docker-hub-release, except for the push commad
  docker-test:
    docker:
    - image: docker:18.06
    working_directory: /go/app
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.05.0-ce
      - checkout
      - run: docker build -t zegl/kube-score:latest .

  docker-hub-release:
    docker:
    - image: docker:18.06
    working_directory: /go/app
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.05.0-ce
      - checkout
      - run: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      - run: docker build -t zegl/kube-score:latest .
      - run: docker push zegl/kube-score:latest

workflows:
  version: 2
  build-and-release:
    jobs:
    - test
    - docker-test
    - docker-hub-release:
        filters:
          branches:
            only:
            - master
        requires:
          - test
